// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SocialCS.Models;
using System;

namespace SocialCS.Migrations
{
    [DbContext(typeof(SocialCSContext))]
    partial class SocialCSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SocialCS.Models.MvcArticles", b =>
                {
                    b.Property<int>("ArticlesID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Text");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Title");

                    b.Property<int?>("UserID");

                    b.HasKey("ArticlesID");

                    b.HasIndex("UserID");

                    b.ToTable("MvcArticles");
                });

            modelBuilder.Entity("SocialCS.Models.MvcComments", b =>
                {
                    b.Property<int>("CommentsID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArtilcesID");

                    b.Property<string>("Author");

                    b.Property<int?>("MvcArticlesArticlesID");

                    b.Property<string>("Text");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Title");

                    b.Property<int?>("UserID");

                    b.HasKey("CommentsID");

                    b.HasIndex("MvcArticlesArticlesID");

                    b.HasIndex("UserID");

                    b.ToTable("MvcComments");
                });

            modelBuilder.Entity("SocialCS.Models.MvcUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("UserID");

                    b.ToTable("MvcUser");
                });

            modelBuilder.Entity("SocialCS.Models.MvcArticles", b =>
                {
                    b.HasOne("SocialCS.Models.MvcUser", "MvcUser")
                        .WithMany("MvcArticles")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("SocialCS.Models.MvcComments", b =>
                {
                    b.HasOne("SocialCS.Models.MvcArticles", "MvcArticles")
                        .WithMany("MvcComments")
                        .HasForeignKey("MvcArticlesArticlesID");

                    b.HasOne("SocialCS.Models.MvcUser", "MvcUser")
                        .WithMany("MvcComments")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
